typography_spectrum: 0.7708298421930522
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.2533991832751781
  lightness: 0.7878204856533557
  saturation: 0.30707699176855385
  rhythmicContrast: 0.650465618353337
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8000364063773304
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Ethel Lebenkoff
  email: ethelethelethel@hotmail.com
  url: 'http://ethelethelethelnow.com'
name: ethelethelethel
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ethel lebenkoff
purpose: []
