typography_spectrum: 0.9078505614306778
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.33877401798963547
  lightness: 0.09934050031006336
  saturation: 0.09815677348524332
  rhythmicContrast: 0.5732377022504807
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.14253357099369168
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Ethel Lebenkoff
  email: ethelethelethel@hotmail.com
  url: 'http://ethelethelethelnow.com'
name: ethelethelethel
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ethel lebenkoff
purpose: []
