typography_spectrum: 0.061882230918854475
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7784287251997739
  lightness: 0.05806916090659797
  saturation: 0.030416904482990503
  rhythmicContrast: 0.32210100581869483
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6658398760482669
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Ethel Lebenkoff
  email: ethelethelethel@hotmail.com
  url: 'http://ethelethelethelnow.com'
name: ethelethelethel
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ethel lebenkoff
purpose: []
